draft of deleting and creating vms

diff --git a/openstackssh b/openstackssh
--- a/openstackssh
+++ b/openstackssh
@@ -1,5 +1,7 @@
 #!/bin/bash
-#set -x
+set -x
+# not we force no strict host key checking as when VM's get rebuilt their
+# host keys will often get regenerated
 NUM_RETRY=10
 SLEEP=$((60 * 1))
 OSCMD=${OSCMD:-openstack}
@@ -35,28 +37,50 @@ fi
 # I am sticking to it ;-)
 function isup()
 {
- #   set -x
+#    set -x
     local s=$1
-
-    #! $OSCMD server ssh $s -- -l nobody -i /dev/null -v -o ConnectTimeout=1 -o ConnectionAttempts=1 true 2>&1 | grep -i  "timed out"
+    local out
+    local rc=0
+    
+    #! $OSCMD server ssh $s -- -l nobody -i /dev/null -v -o "StrictHostKeyChecking no" ConnectTimeout=1 -o ConnectTimeout=1 -o ConnectionAttempts=1 true 2>&1 | grep -i  "timed out"
     # not sure if we really need  ConnectionAttempts=1 so default behaviour for the moment is not to use it
-    ! $OSCMD server ssh $s -- -l nobody -i /dev/null -v -o ConnectTimeout=1 true 2>&1 | grep -i  "timed out"
-    return $?
+    out=$($OSCMD server ssh $s -- -l nobody -i /dev/null -v -o 'StrictHostKeyChecking\ no' -o ConnectTimeout=1 true 2>&1)
+    if [[ $out =~ ^No\ server.*$ ]]; then
+	rc=1
+    elif [[ $out =~ ^.*Operation\ timed\ out.* ]]; then
+	rc=2
+    else
+	rc=0
+    fi
+    return $rc
 }
 
 for ((i=0; i<NUM_RETRY; i++)); do
-    if isup $server; then
-       break;
-    else
-	[[ -z $NERCSSH_SILENT ]] && echo "$server is not ACTIVE...starting it up... be patient" > /dev/stderr
-	if $OSCMD server start $server 2>&1 > /dev/stderr; then
-	    [[ -z $NERCSSH_SILENT ]] && echo "Sent start command : $OSCMD server start $server" > /dev/stderr
-	else
-	    [[ -z $NERCSSH_SILENT ]] && echo "Start command failed will try again if needed" > /dev/stderr
-	fi
-	[[ -z $NERCSSH_SILENT ]] && echo "sleeping for $SLEEP seconds .... while we wait for the system come back up" > /dev/stderr
-	sleep $SLEEP 
-    fi
+    isup $server
+    case $? in
+	0)
+	    # server is up so we don't need to loop
+	    break;
+	    ;;
+	1)
+	    # server does not exist so we must create it.  creation also starts
+	    [[ -z $NERCSSH_SILENT ]] && echo "$server does not EXIST ...creating and starting it up... be patient" > /dev/stderr
+	    [[ -z $CREATE_ARGS && -a $configdir/$server ]] && . $configdir/$server
+	    $OSCMD server create --wait --security-group default  --security-group ssh_only $CREATE_ARGS $server
+	    [[ -n $FLOAT_IP ]] && $OSCMD server add floating ip $server $FLOAT_IP
+	    ;;
+	2)
+	    # server exists but does not seem to be started
+	    [[ -z $NERCSSH_SILENT ]] && echo "$server is not ACTIVE...starting it up... be patient" > /dev/stderr
+	    if $OSCMD server start $server 2>&1 > /dev/stderr; then
+		[[ -z $NERCSSH_SILENT ]] && echo "Sent start command : $OSCMD server start $server" > /dev/stderr
+	    else
+		[[ -z $NERCSSH_SILENT ]] && echo "Start command failed will try again if needed" > /dev/stderr
+	    fi
+	    ;;
+    esac
+    [[ -z $NERCSSH_SILENT ]] && echo "sleeping for $SLEEP seconds .... while we wait for the system come back up" > /dev/stderr
+    sleep $SLEEP 
 done
 
 if ((i==NUM_RETRY)); then
@@ -65,4 +89,4 @@ if ((i==NUM_RETRY)); then
 fi
 shift
 
-exec $OSCMD server ssh $server -- $@
+exec $OSCMD server ssh $server -- -o 'StrictHostKeyChecking\ no' $@
